name: telegram_ui
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: 1.1.6
  flutter_screenutil: ^5.6.1
  flutter_slidable: ^2.0.0
  flutter_launcher_icons: ^0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/ic_launcher_ios.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Gilroy-B
      fonts:
        - asset: assets/fonts/Gilroy-Bold.ttf
    - family: Gilroy-SB
      fonts:
        - asset: assets/fonts/Gilroy-SemiBold.ttf
    - family: Gilroy-M
      fonts:
        - asset: assets/fonts/Gilroy-Medium.ttf

